"""Draft-label helper: run the extractor on a doc and save a draft label file.

Usage:
    uv run python scripts/create_label.py <path/to/invoice.pdf>

What it does:
1. Runs extract_invoice on the supplied document (real Gemini call).
2. Saves the result as a draft label to eval/labels/<stem>.json.
3. Prints the draft so you can spot errors immediately.

After running:
- Open eval/labels/<stem>.json
- Correct any wrong or missing values (leave null for fields genuinely absent)
- Keep the _meta block as-is
- Run the eval harness: uv run python -m eval.run

Repeat for each document you want in the benchmark.
"""

from __future__ import annotations

import asyncio
import json
import sys
from datetime import UTC, datetime
from pathlib import Path

from dotenv import load_dotenv

from services.api.clients import make_client
from services.api.clients.base import VLMError
from services.api.extractor import extract_invoice
from services.api.ingest import IngestError

_LABELS_DIR = Path(__file__).parent.parent / "eval" / "labels"


async def _run(doc_path: Path) -> int:
    load_dotenv()

    try:
        client = make_client()
    except VLMError as exc:
        print(f"[error] {exc}", file=sys.stderr)
        return 1

    print(f"Extracting: {doc_path.name} …")
    try:
        result = await extract_invoice(doc_path, client)
    except IngestError as exc:
        print(f"[error] ingest failed: {exc}", file=sys.stderr)
        return 1
    except VLMError as exc:
        print(f"[error] VLM extraction failed: {exc}", file=sys.stderr)
        return 1

    label = {
        "_meta": {
            "doc_file": doc_path.name,
            "labeled_by": "human",
            "labeled_at": datetime.now(UTC).strftime("%Y-%m-%d"),
            "note": "Draft generated by create_label.py — review and correct before use.",
        },
        **result.model_dump(),
    }

    out_path = _LABELS_DIR / f"{doc_path.stem}.json"
    out_path.write_text(
        json.dumps(label, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    print(json.dumps(label, indent=2, ensure_ascii=False))
    print(f"\n✓ Draft saved → {out_path}")
    print(
        "\nNext steps:\n"
        "  1. Open the file above and correct any wrong/missing values.\n"
        "  2. Leave null for fields genuinely absent in the document.\n"
        "  3. Run: uv run python -m eval.run\n"
    )
    return 0


def main() -> None:
    if len(sys.argv) != 2:
        print(
            "Usage: uv run python scripts/create_label.py <path/to/invoice.pdf>",
            file=sys.stderr,
        )
        sys.exit(1)
    sys.exit(asyncio.run(_run(Path(sys.argv[1]))))


if __name__ == "__main__":
    main()
